### ISSUE TITLE
visual bug unconfirmed incoming stakes

### ISSUE THREAD

**Issue by ThunderousDreamer** [B3-Coin/B3-CoinV2#14]
Incoming stakes show 100% of stake amount instead of 40% of stake amount (60% for MN). example:
incoming unconfirmed stake in wallet: 54.7m, actual stake sent to wallet according to block explorer: 21.8m

https://cdn.discordapp.com/attachments/380422505409675274/385295918276149248/IMG_0779.jpg

**Comment by joshafest** [comment]
Assignment of bounty to this

**Comment by despotak** [comment]
on the same note, FNs show a discrepancy in `Total minted`, `Stake`, and the actual FN reward received

![image](https://user-images.githubusercontent.com/8259004/33495607-c1957972-d6cf-11e7-832b-1318f58b5836.png)

![image](https://user-images.githubusercontent.com/8259004/33495623-db4e6d06-d6cf-11e7-8e84-8fdb13e43854.png)

**Comment by joshafest** [comment]
fixed

**Comment by despotak** [comment]
Thank you @joshafest. I will close the issue when I get the chance to build a qt and confirm.
