### ISSUE TITLE
Fundamental Nodes stop and are no longer in the list after several hours & unequal pay

### ISSUE THREAD

**Issue by KrisBTC** [B3-Coin/B3-CoinV2#17]
Have to start FN back up in console then they will appear for upto 12 hours before disappearing. Also multiple nodes in one wallet are unequal in rewards and others get no rewards at all. After the command start-many, all say successful.

**Comment by joshafest** [comment]
fundamental node rewards are some sort of random, they are not typically masternodes, it is different from that

**Comment by KrisBTC** [comment]
I know the amount is random but is the choosing of the winner's random or is that in a queue? If it is a queue it doesnt seem to appear with me and a few others who have several FN in one wallet.

**Comment by joshafest** [comment]
it was random , but now it becomes queue
