### ISSUE TITLE
Cant install B3coin-qt

### ISSUE THREAD

**Issue by sashrafali12** [B3-Coin/B3-CoinV2#18]
Hello, 

I am kind of new at linux platform. I was trying to install b3coin-qt, but getting this error after the make. 

/usr/bin/ld: cannot find -lboost_filesystem
collect2: error: ld returned 1 exit status
Makefile:558: recipe for target 'b3coin-qt' failed
make: *** [b3coin-qt] Error 1

Can anyone please help me with this.

**Comment by joshafest** [comment]
Please install boost

**Comment by sashrafali12** [comment]
Thanks for the help. it worked!
