### ISSUE TITLE
Can't build on arch linux

### ISSUE THREAD

**Issue by SadMann** [B3-Coin/B3-CoinV2#19]
Hello
Can you please make the wallet compatible with libssl 1.1, cause I can't compile it or make it run on arch linux.

Regards

**Comment by AltFreq** [comment]
I don't run arch and I know its a little different to other builds, but can't you just install the openssl-1.0 package?

**Comment by SadMann** [comment]
openssl-1.0 is installed but ther is many other dependencies that are not saticefied! so it must be a patch that makes it possible to build the wallet on arch.

**Comment by despotak** [comment]
@SadMann I don't have a arch machine to test, but what other dependencies are not working?

**Comment by SadMann** [comment]
@despotak the probleme is that the wallet needs older versions of some packages, but in arch only the new one are installed, and downgrading theme breaks the system. here is the concerned packages:
GCC 7.2.0-3
OpenSSL 1.1.0.g-1 & openssl-1.0 1.0.2.l-1 (don’t know which one was used)
Berkeley DB 5.3.28-3
Boost 1.65.1-2
miniupnpc 2.0.20170509-2

**Comment by SadMann** [comment]
@despotak the probleme is that the wallet needs older versions of some packages, but in arch only the new one are installed, and downgrading theme breaks the system. here is the concerned packages:
GCC 7.2.0-3
OpenSSL 1.1.0.g-1 & openssl-1.0 1.0.2.l-1 (don’t know which one was used)
Berkeley DB 5.3.28-3
Boost 1.65.1-2
miniupnpc 2.0.20170509-2
