### ISSUE TITLE
Unix Build (Low Priority)

### ISSUE THREAD

**Issue by AltFreq** [B3-Coin/B3-CoinV2#22]
Just a quick note in regards to the unix build.

When building one of the dependencies is noted as libssl-dev
This should actually be libssl1.0-dev as any version above 1.1 will have issues with the bitshares component

**Comment by despotak** [comment]
While I understand what you are saying, all linux repos that I'm aware of have the LTS libssl (1.0.x) under the `libssl-dev` nomenclature. `libssl1.0-dev` is not available on older distros (like Ubuntu Xenial 16.04LTS) that many of us use to setup linux nodes.

Yes, if you build libssl yourself, you need to build the LTS version, but for now, I believe, that the `libssl-dev` is the best bet, that covers the vast majority  people.

@AltFreq did you got 1.1 from a package manager while using `libssl-dev` and if yes, which one?

**Comment by AltFreq** [comment]
Yea this makes sense it fine as long as people can find an answer if they need, It did still compile there was just a bunch of errors and I'm not sure how well the SSL component will work.

Using both Debian 9 and an offshoot based on Debian with the same issue when using apt-get install libssl-dev

**Comment by despotak** [comment]
You `apt-get install libssl-dev` and got `libssl1.1.0` on debian? What version? Did they pushed libssl 1.1.0 on Stretch?

**Comment by AltFreq** [comment]
Yea using stretch I get 1.1.0 from libssl-dev

**Comment by cryptokane** [comment]
Regarding this linux build, trying to build from the 3.1.1.1 source from the release section results in Error: Error initializing wallet database environment /home/fmn/.B3-CoinV2!

Seems to be a BerkeleyDB related issue, I have the latest version installed on my vps, when reading through build-unix.txt:

You need Berkeley DB. If you have to build Berkeley DB yourself:
../dist/configure --enable-cxx
make

however, far as I can tell the BDB source isn't packaged with the B3 source, so I think these instructions are a bit lacking.

1. What is the correct version to build?
2. Where is that version downloaded from?

**Comment by despotak** [comment]
Hey @cryptokane. As far as I know, `build-unix.txt` is a remnant of bitcoin codebase. We do not use Berkeley DB on linux, but rather the `leveldb` that is under `/src/leveldb` and you only need to `make libmemenv.a libleveldb.a` in there (but I'm sure you are aware of that part, since it was on your provision script)

**Comment by cryptokane** [comment]
That's the confusing thing for me, since I get no build errors, yet the database wont initialize even after doing a clean make, make "libs" inside of leveldb

The one thing I do notice is when recompiling the wallet itself, it seems to use the new libs from above, but only takes 10-15 seconds to create the binary for b3coind

**Comment by ruoc** [comment]
Used 14.4 version of ubuntu and latest libssl is 1.0, if you using 16, libssl will be latest and you will have to install lower version of libssl to compile

**Comment by despotak** [comment]
According to https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=libssl, `libssl-dev` gets you v1.0.x even on the newest ubuntu suite (bionic)

**Comment by joshafest** [comment]
I think it get resolved
