### ISSUE TITLE
Lost 1 B3 in coin control Inputs, can't spend that input

### ISSUE THREAD

**Issue by ruoc** [B3-Coin/B3-CoinV2#30]
Got 1 input, having 20000001 B3 in wallet, send extra 1 B3 and it get disappear in inputs, can't send 20000001 B3 to burn because insufficient fund

**Comment by joshafest** [comment]
You can send 20M + 1 , the 1 coin is still there but you cannot spend it , to avoid dust transactions

**Comment by ruoc** [comment]
First tx is 20000.001, then i need extra 1 b3 to use as tx fee to burn, but 1 b3 tx disappear and i can't spent, even my balance is 20000.002. 1 b3 tx is not listed in coin control, and it can't be used as tx fee to burn.
I think hide 1 b3 from fn burn tx affect all 1 b3 tx

**Comment by joshafest** [comment]
You should send 2 coins

**Comment by despotak** [comment]
@ruoc To protect the collateral, we hide and make unavailable any input of 1 B3. As @joshafest said, if you need to add more, please send more than 1 B3 (like two or three)
