### ISSUE TITLE
FN start-many or start-alias EXPIRED

### ISSUE THREAD

**Issue by SkyHyperV** [B3-Coin/B3-CoinV2#31]
When running multiple FNs in one wallet using the fundamentalnode.conf, then starting via start-many or start-alias, causes the FN to go back to EXPIRED/REMOVE status after some time (an hour or so).

**Comment by joshafest** [comment]
This is not the issue, many people already running it , it happens when you miss the ping

**Comment by SkyHyperV** [comment]
The same FNs are fine and stay enabled when I run them in separate wallets on the same server.  No other configuration has changed besides putting them into fundamentalnode.conf and doing 'start-many'.  So again, same server, same settings but in one wallet they expire after some time but in separate wallets on same server they stay enabled.

The conf file has the standard config:
rpcuser=b3coinrpc
rpcpassword=MYPASSWORD
rpcallowip=0.0.0.0/0
server=1
daemon=1
listen=1
logtimestamps=1
staking=0
promode=1
externalip=MYIP
bind=MYIP
maxconnections=125

fundamentalnode.conf has:
b3fn01 MYIP:5647 GENKEY TXHASH 1
b3fn02 MYIP:5647 GENKEY TXHASH 1
