### ISSUE TITLE
how to download and setup  linux wallet (ubuntu)

### ISSUE THREAD

**Issue by abudabbour** [B3-Coin/B3-CoinV2#33]
I was trying to download  the wallet on ubuntu, but failed . i recieve messages asa reqired additional mime . 
could you please write down  how to download and install walllet step by step or by vedio.
thanks

**Comment by MadRussian** [comment]
What version of ubuntu? You can do `lsb_release -a` to get that information.
Additionally the message you received is not helpful, at least to me. Would be way more helpful if you pasted your error.

Additionally I created a github repo to run their wallet (master branch), this is experimental. But you can use it minimally to see what packages I installed and in what order as well as how I compiled it:
https://github.com/MadRussian/b3coin-docker

**Comment by despotak** [comment]
@abudabbour we do no offer a Linux (Ubuntu) binary file. If you want to run the wallet on Ubuntu, you have to download the source code and build it yourself. You can find more info at https://github.com/B3-Coin/B3-CoinV2/blob/master/doc/build-unix.txt or try @MadRussian's docker
