### ISSUE TITLE
Wallet does not work on Mac OSX (10.11.14 El Capitan)

### ISSUE THREAD

**Issue by sova** [B3-Coin/B3-CoinV2#38]
This error is thrown when the wallet application is invoked,
![b3 coin wallet mac no worky](https://user-images.githubusercontent.com/451489/34647596-3f964d9e-f343-11e7-8b28-dc7275c572ea.png)
 Just after the splash screen comes up.

**Comment by m2461** [comment]
same here (on OSX 10.11.6)

**Comment by joshafest** [comment]
Please clean the chain. then restart the wallet
