### ISSUE TITLE
COINS NOT SHOWING UP IN WALLET. MAC VERSION v3.1.1.2-B3

### ISSUE THREAD

**Issue by jbm0912** [B3-Coin/B3-CoinV2#40]
Transaction ID: b59e91733423789051cacabd79339c62f4ef2a109d623356914462ff22e7919e

I sent coins from CE to my wallet a few days ago and they have yet to show up in my wallet, however the transaction ID is showing that the coins should be there. Is there anyone that can help with configuring the Mac wallet to get my coins to show. 

Thank you

**Comment by joshafest** [comment]
It is code repository, coinexchange is third party, and this repository is only responsible for “what it does” not for “what you do with it”

**Comment by jbm0912** [comment]
What do you mean? My wallet is having trouble syncing. I need help configuring my wallet. Is there anyone that can help?
