### ISSUE TITLE
B3 price

### ISSUE THREAD

**Issue by kujayago** [B3-Coin/B3-CoinV2#41]
As B3 is listed on 2 exchanges
Coinexchange.io and Yobit.net.
But there is a big price difference in both. 
Coinexchange has 1 satoshi and Yobit 45 satoshi.
Which one is true. 
Pls confirm

**Comment by ThunderousDreamer** [comment]
YoBit is not on the right chain, so they are incorrect at this time.

**Comment by despotak** [comment]
github issues is not the right place for such questions. Please join our discord at https://discordapp.com/invite/ARpuv79

**Comment by jimmybenjamin** [comment]
1000 B3s= 1kb3 and supose to be equal in value but there not kb3 is less value than b3 is. So anyone that had b3 on yobit before kb3 came out your buying and selling b3 on yobit for the correct price. This was before they turned 1,125,000.00b3s into 1125.00kb3 and fucking ripped everyone off. POS
