### ISSUE TITLE
moedas perdidas 

### ISSUE THREAD

**Issue by MANOPONT19** [B3-Coin/B3-CoinV2#42]
minhas moedas nao chegaram na minha carteira

**Comment by MadRussian** [comment]
Translation: my coins did not arrive in my wallet
For general help use discord, this is not for github.
B3 discord: https://discordapp.com/invite/ARpuv79
This issue should be closed.

**Comment by despotak** [comment]
Thank you for the translation @MadRussian.

Issue is closed, as this is a question best answered on discord, and not an issue of the code.
