### ISSUE TITLE
bidding on B3Coin?

### ISSUE THREAD

**Issue by Dima091985** [B3-Coin/B3-CoinV2#44]
Good day. Could you tell me whether in future trades B3Coin?

**Comment by AltFreq** [comment]
These github issues are for issues and requests for enhancements. If you would like questions like this answered your best bet would be the discord channel as devs will likely ignore this as they are busy working in the coin. https://discord.gg/vtRHCA

**Comment by despotak** [comment]
github issues is not the right place for such questions. Please join our discord at https://discordapp.com/invite/ARpuv79
