### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wankosensei777** [B3-Coin/B3-CoinV2#45]
apologize in advance that English is not my first language .

I had 600k B3 coins in coinexchange. It vanished yesterday.

I didn't action to withdraw B3 coins by myself. Even though, My coins are supposed to withdraw on history. And I couldn't find my coins in my account. I don't understand this. Where are my coins? Who ordered withdraw? Not me. Is someone stole my account?
I asked support already. But support doesn't respond yet.

**Comment by wankosensei777** [comment]
I wanna ask.  What should I do something?

**Comment by despotak** [comment]
github issues is not the right place for such questions. Please join our discord at https://discordapp.com/invite/ARpuv79

Please contact Coinexchange Support for that. We are not in control of their wallet.
