### ISSUE TITLE
Coins stuck in yobit

### ISSUE THREAD

**Issue by mediumjack1** [B3-Coin/B3-CoinV2#46]
I have over17000  coins on Yobit and can't move them because yobit tells me that my wallet is under maintenance. I have emailed their support over a week ago and not heard back from them. ayone know how to go about moving my tokens?

**Comment by xkira1995** [comment]
Don't use YoBit to buy the coins. B3 team has been trying to get YoBit to update their wallet and YoBit won't get back to them. Buy KB3 from CoinExchange io instead. KB3 is the soft fork of B3. 1 KB3 = 1000 B3. YoBit is a pump and dump community exchange mostly.

**Comment by joshafest** [comment]
Exchangers are third party, nothing to do with core .

**Comment by mediumjack1** [comment]
These are relatively unhelpful comments. I have used YoBit because that is where I initially purchased the tokens. Now they are in suspention mode and I cannot move them. I am not intending on buying more of the shit token that has gone to shit on another exchange, without recouping some of my initial investment by getting my B3 out of Yobit first.

**Comment by joshafest** [comment]
This is core code ... and nothing to do with what you are searching... we or anyone is not responsible if you buy from yobit even it was mentioned not to use it.

**Comment by rohingosling** [comment]
@mediumjack1 
You can get general help for non-code related issues, from the B3 Coin Discord channels. In general though, there is nothing anyone can do about people who have coins stuck on YoBit. YoBit missed a critical wallet update many months ago, and so all coins in YoBit at the moment are all on the wrong chain. The best thing you can do, is sell the B3 you have on YoBit for BTC, and then buy back into B3 on an exchange that is running that correct wallet. Before you buy B3 on any exchange, check with the helpers in Discord first, to make sure you buy from the most optimal exchange. And then after making sure 'you' also have the latest wallet, send your B3 to your local wallet. Don't leave crypto on any exchange. Always keep your crypto in cold storage using your local wallet.
