### ISSUE TITLE
5 Digit kB3 Send Error

### ISSUE THREAD

**Issue by jnguyener** [B3-Coin/B3-CoinV2#49]
When you are trying to send kB3 you cannot put more than 5 decimals. If you switch it to B3 to send you're able to send more than the 5 decimals.

**Comment by ThunderousDreamer** [comment]
duplicate of issue #48

**Comment by despotak** [comment]
Closed as it is duplicate of #48 

Thank you both @jnguyener and @ThunderousDreamer for posting this.
