### ISSUE TITLE
Pose Score of fundamental node does not decrease as expected 

### ISSUE THREAD

**Issue by engzizo79** [B3-Coin/B3-CoinV2#52]
The nScanningErrorCount property should decrease when scanning is successful and increase if not. However, it seems that fns stay many hours at the same positive score. The debug log shows that pings arrive every 5 minutes as expected, but pose score stays the same. Issue has been noticed on remotely started fns on linux Ubuntu 16.04

**Comment by engzizo79** [comment]
Also the new wallet version 3.1.2 always shows a pose score of 0 when the command 'fundamentalnode pose' is run

**Comment by joshafest** [comment]
PoS is type of state, yes it should decrease if scan is successful nice idea. Please make a proposal, and you will be added to credits

**Comment by AltFreq07** [comment]
I have been monitoring my nodes over a few days. Every 4 hours or so the whole network should be scanned by the wallet either giving a positive nErrorType on a SCANNING_SUCCESS decreasing the nScanningErrorCount by 1 or for any other error increasing nScanningErrorCount by 1.

I have a few nodes that have a pose score or nScanningErrorCount >  0 which should be either decreasing by 1 or increasing by 1 at least every four hours according to a comment in fn-service.h
These nodes have their pose score updated maybe once every 8-10 hours if lucky with majority of them not changing at all.

**Comment by joshafest** [comment]
Please, label enhancements

**Comment by engzizo79** [comment]
I was wondering if this problem is related to the setting that wallets don't connect for 24 hours by default to wallets that were 'misbehaving', therefore it would actually take 24 hours + x for any decrease to happen?

**Comment by engzizo79** [comment]
I am still trying to understand the code, from fn-service.cpp it seems that only 1% of the nodes are scanned per block, which would make it 100 blocks on average per scan, that is more than 10 hours and not 4. Also I'm not sure how it is controlled that the scanning node is not the one that has a problem with the connection when it broadcasts the problem?
I think it would be important to increase the frequency of scanning the higher the pose score is to make recovery time reasonable. I don't know how rank is determined, and obviously only the top 1% in rank will be scanned each block

**Comment by joshafest** [comment]
I think the issue resolved, if not re-open it
