### ISSUE TITLE
RPC - sendtoaddress

### ISSUE THREAD

**Issue by AltFreq07** [B3-Coin/B3-CoinV2#58]
In order to make my site fully automatic I'm looking for a way to help me burn the coins using rpc. 
The solution seems to be in the command sendtoaddress <address> <amount> <IsFNPayment|True|False> 
But when typing for example 
`b3coind sendtoaddress ST74QxXZefiaX8vswWXxRcf3N39UayH4Ww 20000.001 true`
It seems to just send it as a normal transaction. Am I using this command wrong or is it just not functioning as intended yet?

Thanks

**Comment by AltFreq07** [comment]
Anyone had any luck running this command to burn for a FN yet?

**Comment by joshafest** [comment]
try now it should work.
