### ISSUE TITLE
Blackcoin name in wallet

### ISSUE THREAD

**Issue by ThunderousDreamer** [B3-Coin/B3-CoinV2#64]
The word 'blackcoin' still shows up on various wallet windows/messages. Can this be fixed and replaced with B3coin?

Example: The debug window

**Comment by SkyHyperV** [comment]
Where? Can you show exact examples?

**Comment by ThunderousDreamer** [comment]
Example below is a Windows wallet on Windows server 2016 OS with Dutch localization settings. 

<img width="738" alt="screen shot 2018-04-09 at 23 27 36" src="https://user-images.githubusercontent.com/31323882/38539602-b53ab500-3c4d-11e8-9af7-6e1ec56d9624.png">

**Comment by SkyHyperV** [comment]
I see no issues on the Windows, Linux or Mac version of 3.1.2.2. I also grepped through the entire Qt code where these Qt windows are built and there is no reference to "Blackcoin". In my Mac version, I see B3-Coin everywhere.  See attached.

![image](https://user-images.githubusercontent.com/31451171/38586783-c59f1dcc-3ce4-11e8-84ad-26b02560aaed.png)

![image](https://user-images.githubusercontent.com/31451171/38586774-b962a4ac-3ce4-11e8-83cb-8ee78d08a085.png)

**Comment by ThunderousDreamer** [comment]
Could this be a localization issue? I don't see this issue on my English wallets either. If so, where would the wallet pull these variables from for other languages? Is there maybe a remote source somewhere, where the wallet application looks for for translations?

Just confirming I am using 3.1.1.2 in my screenshot displaying the Blackcoin text:
![image](https://user-images.githubusercontent.com/31323882/38587225-919b6f9e-3cd5-11e8-8673-f1713555900e.png)

**Comment by SkyHyperV** [comment]
Yes, it appears to be a localization issue. I updated the forms and submitted a pull request to update the code. See pull request that is pending review: https://github.com/B3-Coin/B3-CoinV2/pull/65

**Comment by sarvjeet04** [comment]
Who to make kb3 wallet

**Comment by sarvjeet04** [comment]
I am mobile phone usegar

**Comment by joshafest** [comment]
@sarvjeet04 this is not related issue
