### ISSUE TITLE
Wallet isn't synchronizing

### ISSUE THREAD

**Issue by Dasani84** [B3-Coin/B3-CoinV2#67]
Hi there, 

I have a wallet kinda stuck... the issue started with not getting stakes going through, they are just staying grey in the wallet... at that time kb3 was inactive in coinmarketcap, I thought it could be related to this. 

After the restart of my pc I've noticed that it is keep staying out of sync - no metter how many times I restart the wallet, nothing helps. I have 16 active connections and wallet is v 3.1.2.2. Windows 10. Can I get help with this issue?

**Comment by Dasani84** [comment]
So, how it was recommended, I am deleting everything from appdata/roaming/b3coin-v2 exept wallet file. It is synchronizing with the network now from a very beginning I guess... Will update the post if the issues will be fixed.

**Comment by Dasani84** [comment]
ok, it worked :)

**Comment by Dasani84** [comment]
is anyone checking github for this project at all I wounder? 👎

**Comment by Sayazuri** [comment]
No there is no way to accept them because you staked them while you are not synchronized

**Comment by ekidwell4** [comment]
Dead project eh?

**Comment by AltFreq** [comment]
Project is not dead, we answer questions in our discord
https://discord.gg/sY8JAGM
