### ISSUE TITLE
I did not received on wallet

### ISSUE THREAD

**Issue by igoraguillar** [B3-Coin/B3-CoinV2#69]
;
On Windows 10 platform, =v3.1.2.2 -

I have sent = coinexchange to the same wallet address
the  deposit never showed up in the wallet, but shows on the blockchain

i have sent a email to coineschange and received this answer:

Desativar para: inglês
Hi Igor Aguillar,

This withdrawal has been successfully processed and has been confirmed on the blockchain.

https://chainz.cryptoid.info/b3/tx.dws?1acf69c6e39f6ebd6ba56e48d9bfdba3a05c3a1aae435eade935e27097023ae0.htm

This verifies that the withdrawal had no issue on our end of the transaction. 

If you continue to have a problem receiving the funds you will need to contact support from the other end of the transaction.

On certain Bitcoin based blockchains, you may notice “Not Yet Redeemed” as the transaction status.

This means that the transaction is complete, but has not been used as input for another transaction.

Your coins have been received but not yet spent.

Update and sync your wallet in order to see the coins reflected correctly.

Sincerely,

CoinExchange.io Support Team

**Comment by joshafest** [comment]
Please go to discord either or on bitcointalk for support, 
You need to run 
“repairwallet” in rpc console , make sure wallet is fully synced
