### ISSUE TITLE
Can't compile from source in Ubuntu Linux 18.04 LTS

### ISSUE THREAD

**Issue by satoshi-ninja** [B3-Coin/B3-CoinV2#70]
Anyway I try I get the following error:
`Makefile:1418: recipe for target 'build/txdb-leveldb.o' failed`
`make: *** [build/txdb-leveldb.o] Error 1`

**Comment by james1233** [comment]
same problem here

**Comment by SkyHyperV** [comment]
Use these steps for Ubuntu 18.04:

1)    sudo apt-get update && sudo apt-get upgrade -y
2)    reboot
3)    sudo apt-get install -y build-essential libssl1.0-dev libdb++-dev libboost-all-dev libqrencode-dev
4)    wget https://github.com/B3-Coin/B3-CoinV2/archive/v3.1.2.2.tar.gz
5)    tar zxvf v3.1.2.2.tar.gz
6)    cd ~/B3-CoinV2-3.1.2.2/src/leveldb && make clean && make libmemenv.a libleveldb.a && cd .. && make -f makefile.unix
7)    strip b3coind

You should now have a b3coind (wallet daemon binary/executable) that you can move into /usr/bin/ directory or just run from wherever you like.
