### ISSUE TITLE
Computer crash - local drive wallet erased

### ISSUE THREAD

**Issue by paul-tombakian** [B3-Coin/B3-CoinV2#72]
I transferred 891456.806 on from an exchange to my local drive wallet I downloaded from here.
My computer crashed and I lost the wallet.  is there any chance to recover.  I have the receiving address that I took from the exchange that I sent my coins to?  Can that address be used to recover my coins.  I have downloaded a new wallet, when I enter the receiving address I still see no coins after the sync.  
Any suggestions?

**Comment by AltFreq07** [comment]
Hey Paul, 
Do you have access to the private key or wallet.dat containing the address?

**Comment by paul-tombakian** [comment]
Hi,
No, I do not. In COINEXCHANGE.io shows 891456.806 B3 coin withdrawal Time: 2018-01-13 05:18:54 , Receiving address - SbDMdNUkwiiViuyyDgHfebg7KKvZvkT5gS , TXID - 97124f28aba57f7fa526ee59e56db0dd5366510f5955b971cbbe09c96977766e
Thank you
Paul Tombakian

**Comment by joshafest** [comment]
@paul please try dumpprivkey command , if it works it’s all fine , if not then we need further details

**Comment by paul-tombakian** [comment]
Hi,
21:39:58 Welcome to the B3-Coin RPC console.
Use up and down arrows to navigate history, and Ctrl-L to clear screen.
Type help for an overview of available commands.
05:27:18 dumpprivkey
05:27:18 dumpprivkey <b3coinaddress>
Reveals the private key corresponding to <b3coinaddress>. (code -1)
05:28:17 dumpprivkey <b3coinaddress>
05:28:17 Invalid B3-Coin address (code -5)
Thank you
 Paul Tombakian

**Comment by paul-tombakian** [comment]
I tried. Did not help. Couldn't see any KB3 coins. What further details needed?
Thank you  Paul Tombakian

**Comment by AltFreq07** [comment]
If you do no have a backup of your private key or wallet.dat then it is
impossible to recover your coins.

**Comment by paul-tombakian** [comment]
Thank you Paul Tombakian
