### ISSUE TITLE
PAUL-Tombakian5656

### ISSUE THREAD

**Issue by paul-tombakian** [B3-Coin/B3-CoinV2#73]
I transferred 891456.806 B3 coins from Coinexchange.io to my local drive wallet B3-Coin-Wallet.
My computer crashed and I lost the wallet. I do not have backup of private key or wallet.dat. 
Coinexchange.io provided me hash number for that transaction.
Any suggestions?

**Comment by AltFreq** [comment]
Without the private key or wallet.dat its impossible. You could try some
kind of file recovery software to try and recover the wallet.dat.

You need either the wallet.dat or private key to access your address. If
there was other ways to get access to your coins then it wouldn't be very
secure and anyone would be able to get access.

**Comment by paul-tombakian** [comment]
Hi,
Thanks for your advise. I downloaded file recovery software and
was able to recover wallet.dat file from my crashed hard drive and get my B3 coins.
Thank you

**Comment by AltFreq07** [comment]
Wow lucky :) Congratulations
